apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-principal-deployment
  labels:
    app: service-principal-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-principal-deployment
  template:
    metadata:
      labels:
        app: service-principal-deployment
    spec:
      containers:
      - name: service-principal-deployment
        image: registry.digitalocean.com/front-registry/back-end@registry.digitalocean.com/front-registry/back-end@sha256:73fc23a231ddb9d5b0460920352b25eac5602cdd9916de2e7a5460785138ad90
        ports:
        - containerPort: 3000