apiVersion: apps/v1
kind: Deployment
metadata:
  name: download-deployment
  labels:
    app: download-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: download-deployment
  template:
    metadata:
      labels:
        app: download-deployment
    spec:
      containers:
      - name: download-deployment
        image: registry.digitalocean.com/front-registry/service-data@registry.digitalocean.com/front-registry/service-data@sha256:500bef0fde9a56518d38fdb92feed9a1646411b5d22003a7795b657f65992e89
        ports:
        - containerPort: 3010