apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multi-service-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - app.dar.reformaperu.org
    - serviceprincipal.app.dar.reformaperu.org
    - download.app.dar.reformaperu.org
    secretName: tls-secret
  rules:
  - host: app.dar.reformaperu.org           # Frontend service
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontservice
            port:
              number: 80
  - host: serviceprincipal.app.dar.reformaperu.org  # Service principal
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: principalservice
            port:
              number: 80
  - host: download.app.dar.reformaperu.org  # Download service
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: downloadservice
            port:
              number: 80